#define TAPPING_TERM 500
#define TAPPING_TERM_PER_KEY

#define QUICK_TAP_TERM 100
#define QUICK_TAP_TERM_PER_KEY

#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define COMBO_TERM 25
#define COMBO_STRICT_TIMER
#define COMBO_TERM_PER_COMBO

#define RETRO_TAPPING

#undef SPLIT_LED_STATE_ENABLE

#ifdef AUDIO_ENABLE
#define VOLUME 40
#define STARTUP_SONG SONG(MARIO_MUSHROOM)
#define GOODBYE_SONG SONG(MARIO_GAMEOVER)
#define AUDIO_DAC_SAMPLE_MAX 4095U * VOLUME / 100
#endif
